### PR TITLE
Added update function

### PR DESCRIPTION
**Pull request by PabloLefort**

### CODE REVIEW

**Comment by sambs** [comment]
Hi Payblo, thanks for this. 

If your intention is to permit updating of the max date restriction, I think this can be done without adding any new attributes. Can you try this branch https://github.com/sambs/angular-sb-date-select/tree/dynamic-min-max and let me know if you can see any issues?

**Comment by PabloLefort** [comment]
Hi @sambs!
All right, so, using that branch will allow this
```html
<div class="sb-date-select" sb-date-select="" ng-model="myModel.birthday" max="myModel.dinamicMaxDate">
</div>
```
and in the controller go changing it?

Thanks in advance :rocket:

**Comment by sambs** [comment]
Pretty much. I think you'll need to use a template expression in the max attr though:

```javascript
<div class="sb-date-select" sb-date-select="" ng-model="myModel.birthday" max="{{myModel.dinamicMaxDate}}">
</div>
```

**Comment by PabloLefort** [comment]
:man_facepalming: i forgot it.
Perfect, well, will it merged?

**Comment by PabloLefort** [comment]
Very thanks! @sambs :clap: :smile:

**Comment by sambs** [comment]
Oops, merged the wrong pull request. All merged and published now though.

**Comment by PabloLefort** [comment]
Yes, i see the revert

**Pull request merged**
